export interface Applicant{
    applicantID: number | null,
    firstName: string | null,
    lastName: string | null,
    emailAddress: string | null,
    phoneNumber:string | null,
    collegeName:string | null,
    higestQualification:string | null,
    highestQualificationName:string | null,
    higestQualificationPercentage:string | null,
    matricPercentage:string | null,
    intermediatePercentage:string | null,
    skills:string | null,
    statusId:number | null,
    comment:string | null,
    assignedToCompany:number | null,
    registeredDate:Date | null,
    clientId:string | null,
    isActive:boolean | null,
    collegeId:number | null,
}
